### ISSUE TITLE
Catch file permissions exceptions in RootDiscovery

### ISSUE THREAD

**Issue by tgerulaitis** [meanbee/libmageconf#4]
If `RootDiscovery` encounters a file it can see (parent directory readable), but can't read (no read permission on the file/directory itself), it throws an exception:

```
In RootDiscovery.php line 150:

  [UnexpectedValueException]
  RecursiveDirectoryIterator::__construct(/path/to/magento/var/export/email): failed to open dir: Permission denied
```

These should be caught and logged/ignored, not bubbled up.

**Comment by bobbyshaw** [comment]
Closing as this repo is no longer maintained and will be marked as read-only.
